/**
 * Extraction domain types for ApplyAlert.
 *
 * Represents the AI extraction lifecycle and structured results.
 */

import type { OpportunityType, FundingInfo } from './opportunity';
import type { DeadlineKind } from './deadline';

export type ExtractionStatus =
  | 'PENDING'
  | 'PROCESSING'
  | 'READY_FOR_REVIEW'
  | 'FAILED'
  | 'CANCELLED';

export type ExtractionErrorCode =
  | 'EXTRACTION_FAILED'
  | 'EXTRACTION_TIMEOUT'
  | 'EXTRACTION_RATE_LIMITED'
  | 'SOURCE_TOO_LARGE'
  | 'INVALID_EXTRACTION_RESULT'
  | 'VISUAL_EXTRACTION_FAILED'
  | 'PROVIDER_ERROR';

/**
 * AI-extracted representation of a Deadline Candidate.
 * The AI generates this, and we validate/score it before presentation.
 */
export interface ExtractedDeadlineCandidate {
  readonly date: string | null;
  readonly time: string | null;
  readonly timezone: string | null;
  readonly kind: DeadlineKind;
  readonly label: string | null;
  readonly confidence: number;
  readonly evidence: string | null;
}

/**
 * Structured output generated by the AI extraction.
 */
export interface ExtractionResult {
  readonly title: string | null;
  readonly organization: string | null;
  readonly opportunityType: OpportunityType | null;
  readonly summary: string | null;
  readonly location: string | null;
  readonly funding: FundingInfo | null;
  readonly applicationUrl: string | null;
  
  /** 
   * The primary deadline identified by the AI.
   * If null, we assume NONE_STATED or AMBIGUOUS (if candidates exist).
   */
  readonly primaryDeadline: ExtractedDeadlineCandidate | null;
  
  /**
   * Other dates found in the source that could be the deadline.
   */
  readonly alternativeDeadlines: readonly ExtractedDeadlineCandidate[];
  
  readonly eligibility: readonly string[];
  readonly requiredDocuments: readonly string[];
}

export type ExtractionConfidenceLevel = 'HIGH' | 'MEDIUM' | 'LOW' | 'NEEDS_CONFIRMATION';

/**
 * System warnings added during deterministic validation.
 */
export type ExtractionWarningCode =
  | 'MULTIPLE_DEADLINES'
  | 'DEADLINE_YEAR_UNCLEAR'
  | 'DEADLINE_TIMEZONE_UNCLEAR'
  | 'DEADLINE_EVIDENCE_WEAK'
  | 'NO_DEADLINE_FOUND'
  | 'APPLICATION_URL_UNCERTAIN'
  | 'IMAGE_TEXT_UNCLEAR'
  | 'SOURCE_CONTENT_INCOMPLETE';

/**
 * Core Extraction database entity.
 */
export interface Extraction {
  readonly id: string;
  readonly importId: string;
  readonly userId: string;
  readonly status: ExtractionStatus;
  
  readonly provider: string | null;
  readonly model: string | null;
  readonly promptVersion: string | null;
  readonly schemaVersion: string | null;
  
  /** The fully validated AI result. Null until READY_FOR_REVIEW. */
  readonly result: ExtractionResult | null;
  
  /** Our computed confidence based on AI score + deterministic validation. */
  readonly confidenceLevel: ExtractionConfidenceLevel | null;
  
  readonly warnings: readonly ExtractionWarningCode[];
  
  readonly errorCode: ExtractionErrorCode | null;
  readonly errorMessage: string | null;
  
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly processingStartedAt: string | null;
  readonly processingCompletedAt: string | null;
}
